name: Auto-merge Codex PRs

on:
  pull_request_target:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-auto-merge:
    # Only run for PRs from Codex (tweak the list as needed)
    if: >
      github.event.pull_request.user.login == 'github-codex[bot]' ||
      github.event.pull_request.user.login == 'codex-bot' ||
      github.event.pull_request.user.login == 'codex'
    runs-on: ubuntu-latest
    steps:
      - name: Guardrails (skip drafts or closed PRs)
        run: |
          if [ "${{ github.event.pull_request.draft }}" = "true" ]; then
            echo "PR is a draft. Skipping."
            exit 78
          fi
          if [ "${{ github.event.pull_request.state }}" != "open" ]; then
            echo "PR is not open. Skipping."
            exit 78
          fi

      - name: Enable auto-merge (merge when checks pass)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          number=${{ github.event.pull_request.number }}
          # Choose your merge method: --merge | --squash | --rebase
          gh pr merge "$number" --auto --merge
